// data.js or mockData.js

export const mockSystemLogs = [
    {
        id: 1,
        dateTime: '2025-07-11 10:45:00',
        deviceId: 'PS01-DEV',
        component: 'Valve Actuator',
        event: 'High pH level detected',
        details: 'Reading: 8.9 pH',
        status: 'Warning',
    },
    {
        id: 2,
        dateTime: '2025-07-11 10:46:30',
        deviceId: 'PS02-DEV',
        component: 'Main Pump',
        event: 'Pump restarted by system',
        details: 'Automatic restart protocol',
        status: 'Success',
    },
    {
        id: 3,
        dateTime: '2025-07-11 10:47:15',
        deviceId: 'PS01-DEV',
        component: 'Temp Sensor',
        event: 'Sensor offline',
        details: 'No data received',
        status: 'Error',
    },
    {
        id: 4,
        dateTime: '2025-07-11 10:48:00',
        deviceId: 'PS01-DEV',
        component: 'Valve Actuator',
        event: 'Valve opened manually',
        details: 'Action by: admin_user',
        status: 'Success',
    },
    {
        id: 5,
        dateTime: '2025-07-11 10:49:22',
        deviceId: 'PS02-DEV',
        component: 'Flow Meter',
        event: 'Abnormal flow rate',
        details: 'Reading: 12.5 L/min',
        status: 'Warning',
    },
    {
        id: 6,
        dateTime: '2025-07-11 10:50:05',
        deviceId: 'PS04-DEV',
        component: 'Filtration System',
        event: 'Filter cleaned',
        details: 'Cycle complete',
        status: 'Success',
    },
    {
        id: 7,
        dateTime: '2025-07-11 10:51:10',
        deviceId: 'PS02-DEV',
        component: 'pH Sensor',
        event: 'Calibration required',
        details: 'Last cal: 2025-06-10',
        status: 'Info',
    },
    {
        id: 8,
        dateTime: '2025-07-11 10:52:00',
        deviceId: 'PS03-DEV',
        component: 'Dosing Pump',
        event: 'Injection rate adjusted',
        details: 'New rate: 5 mL/min',
        status: 'Success',
    },
];

export const userLogs = [
  {
    id: 1,
    dateTime: "2025-07-20T09:00:00.000Z",
    username: "john.doe",
    fullname: "John Doe",
    action: "Logged in successfully",
    type: "Account",
  },
  {
    id: 2,
    dateTime: "2025-07-20T09:05:15.000Z",
    username: "jane.smith",
    fullname: "Jane Smith",
    action: "Shut off water valve: 'Main Inlet Valve'",
    type: "Valve",
  },
  {
    id: 3,
    dateTime: "2025-07-20T09:10:30.000Z",
    username: "alice.wonder",
    fullname: "Alice Wonderland",
    action: "Changed hardware device parameter: 'pH sensor' to 7.2 (from 6.8)",
    type: "Configuration",
  },
  {
    id: 4,
    dateTime: "2025-07-20T09:15:45.000Z",
    username: "john.doe",
    fullname: "John Doe",
    action: "Updated water change interval: 'Tank 1' to 24 hours (from 48 hours)",
    type: "Configuration",
  },
  {
    id: 5,
    dateTime: "2025-07-20T09:20:00.000Z",
    username: "bob.builder",
    fullname: "Bob Builder",
    action: "Changed hardware device parameter: 'Turbidity sensor' to 5 NTU (from 8 NTU)",
    type: "Configuration",
  },
  {
    id: 6,
    dateTime: "2025-07-20T09:25:20.000Z",
    username: "jane.smith",
    fullname: "Jane Smith",
    action: "Updated account details for 'john.doe': changed password",
    type: "Admin",
  },
  {
    id: 7,
    dateTime: "2025-07-20T09:30:40.000Z",
    username: "alice.wonder",
    fullname: "Alice Wonderland",
    action: "Changed hardware device parameter: 'TDS sensor' to 150 ppm (from 180 ppm)",
    type: "Configuration",
  },
  {
    id: 8,
    dateTime: "2025-07-20T09:35:05.000Z",
    username: "john.doe",
    fullname: "John Doe",
    action: "Opened water valve: 'Discharge Valve Unit B'",
    type: "Valve",
  },
  {
    id: 9,
    dateTime: "2025-07-20T09:40:10.000Z",
    username: "bob.builder",
    fullname: "Bob Builder",
    action: "Changed hardware device parameter: 'Temperature sensor' to 25.0 °C (from 26.5 °C)",
    type: "Configuration",
  },
  {
    id: 10,
    dateTime: "2025-07-20T09:45:30.000Z",
    username: "jane.smith",
    fullname: "Jane Smith",
    action: "Logged out",
    type: "Account",
  },
  {
    id: 11,
    dateTime: "2025-07-20T10:00:10.000Z",
    username: "john.doe",
    fullname: "John Doe",
    action: "Created new user account: 'new.engineer'",
    type: "Admin",
  },
  {
    id: 12,
    dateTime: "2025-07-20T10:05:00.000Z",
    username: "alice.wonder",
    fullname: "Alice Wonderland",
    action: "Performed system diagnostic on 'Sensor Hub 3'",
    type: "Configuration",
  },
  {
    id: 13,
    dateTime: "2025-07-20T10:10:20.000Z",
    username: "bob.builder",
    fullname: "Bob Builder",
    action: "Acknowledged low pressure alarm: 'Pump Station 1'",
    type: "Acknowledgement",
  },
  {
    id: 14,
    dateTime: "2025-07-14T09:24:03.000Z",
    username: "dora.explo",
    fullname: "Dora The Explorer",
    action: "User triggered a system error",
    type: "Account",
  },
];