// data.js or mockData.js

export const mockSystemLogs = [
    {
        id: 1,
        dateTime: '2025-07-11 10:45:00',
        deviceId: 'PS01-DEV',
        component: 'Valve Actuator',
        event: 'High pH level detected',
        details: 'Reading: 8.9 pH',
        status: 'Warning',
    },
    {
        id: 2,
        dateTime: '2025-07-11 10:46:30',
        deviceId: 'PS02-DEV',
        component: 'Main Pump',
        event: 'Pump restarted by system',
        details: 'Automatic restart protocol',
        status: 'Success',
    },
    {
        id: 3,
        dateTime: '2025-07-11 10:47:15',
        deviceId: 'PS01-DEV',
        component: 'Temp Sensor',
        event: 'Sensor offline',
        details: 'No data received',
        status: 'Error',
    },
    {
        id: 4,
        dateTime: '2025-07-11 10:48:00',
        deviceId: 'PS01-DEV',
        component: 'Valve Actuator',
        event: 'Valve opened manually',
        details: 'Action by: admin_user',
        status: 'Success',
    },
    {
        id: 5,
        dateTime: '2025-07-11 10:49:22',
        deviceId: 'PS02-DEV',
        component: 'Flow Meter',
        event: 'Abnormal flow rate',
        details: 'Reading: 12.5 L/min',
        status: 'Warning',
    },
    {
        id: 6,
        dateTime: '2025-07-11 10:50:05',
        deviceId: 'PS04-DEV',
        component: 'Filtration System',
        event: 'Filter cleaned',
        details: 'Cycle complete',
        status: 'Success',
    },
    {
        id: 7,
        dateTime: '2025-07-11 10:51:10',
        deviceId: 'PS02-DEV',
        component: 'pH Sensor',
        event: 'Calibration required',
        details: 'Last cal: 2025-06-10',
        status: 'Info',
    },
    {
        id: 8,
        dateTime: '2025-07-11 10:52:00',
        deviceId: 'PS03-DEV',
        component: 'Dosing Pump',
        event: 'Injection rate adjusted',
        details: 'New rate: 5 mL/min',
        status: 'Success',
    },
];